<div class="container">
	<div class="login gradAndBoxShad">
	<!--	<?=$error?>  -->
		<h2>Identification</h2>
		<form method="post" class="form-horizontal">
			<!-- login -->
			
			<div class="row control-group">
	            <div class="form-group col-xs-12 floating-label-form-group controls">
	                <label>email</label>
	                <input type="text" class="form-control"  name="email" >
	                <p class="help-block text-danger"></p>
	            </div>
	         </div>
			<!-- password -->
			
			<div class="row control-group">
	            <div class="form-group col-xs-12 floating-label-form-group controls">
	                <label>password</label>
	                <input type="text" class="form-control"  name="password" >
	                <p class="help-block text-danger"></p>
	            </div>
	         </div>
			<!-- Connexion -->
			<div>
				<button type="submit" name="login" value="login">Connexion</button>
			</div>
		</form>
	</div>

	<div class="login gradAndBoxShad">
		<h2>enregistrement :</h2>

		<form method="post">		    	
			<div class="row control-group">
		    				
	            <div class="form-group col-xs-12 floating-label-form-group controls">
	                <label>pseudo</label>
	                <input type="text" class="form-control"  name="pseudo"  >
	                <p class="help-block text-danger"></p>
	            </div>
	        </div>
			<!-- e-mail -->
			
			<div class="row control-group">
	            <div class="form-group col-xs-12 floating-label-form-group controls">
	                <label>email</label>
	                <input type="text" class="form-control"  name="email" >
	                <p class="help-block text-danger"></p>
	            </div>
	         </div>
			<!-- password -->
			
		    <div class="row control-group">
	            <div class="form-group col-xs-12 floating-label-form-group controls">
	                <label>password</label>
	                <input type="text" class="form-control"  name="password" >
	                <p class="help-block text-danger"></p>
	            </div>
	         </div>
		   
			<div class="row control-group">
	            <div class="form-group col-xs-12 floating-label-form-group controls">
	                <label>confirm password</label>
	                <input type="text" class="form-control"  name="password2" >
	                <p class="help-block text-danger"></p>
	            </div>
	         </div>
			<!-- valid -->
			<div>
				<button type="submit" name="register" value="register">Envoyer</button>
			</div>
		</form>
	</div>
</div>
 

                  
               