<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
	<title>projet solo</title>
	<link href="public/styles/bootstrap.min.css" rel="stylesheet">
    <link href="public/styles/style.css" rel="stylesheet">
	<script src="public/scripts/jquery.min.js"></script>
    <script src="public/scripts/bootstrap.min.js"></script>
</head>
<body>
	<html>
		<div class="container-fluid">
		
			<?php require ("apps/header.php");?>
			<?php require ("apps/menu.php");?>
			<?php require ("apps/content.php");?>
			<?php require ("apps/footer.php");?>
		</div>
	</html>
</body>